id: IECEA5952
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:13:29+00:00'
last_modified: '2022-06-08T12:03:05.402856+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16790
  title: བོན་གྱི་མཛོད་སྒོ་སྒྲ་འགྲེལ་འཕྲུལ་གྱི་ལྡེ་མིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4A5A:
      image_group_id: I8LS16800
      title: ''
      total_pages: 360
      order: 1
      base_file: 4A5A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
