id: P009582
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:39:13.418632
source_metadata:
  id: bdr:W8LS16790
  title: བོན་གྱི་མཛོད་སྒོ་སྒྲ་འགྲེལ་འཕྲུལ་གྱི་ལྡེ་མིག
  author: ''
  volumes:
    7cddf9b136a44956b0ad93f963153c09:
      image_group_id: I8LS16800
      title: ''
      volume_number: 1
      total_pages: 360
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
